[project]
name = "outlook-client-service"
version = "0.1.0"
description = "A FastAPI service for interacting with Outlook calendar APIs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv>=1.0.0",
    "pydantic",
    "itsdangerous",
    "calendar-client-api",
    "outlook-client-impl",
    "intelligent-app-service",
    "chat-client-api",
    "slack-client-impl",
]

[project.optional-dependencies]
test = [
    "pytest>=7.0.0",
    "pytest-mock>=3.10.0",
    "httpx",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/outlook_client_service"]

[tool.hatch.build.targets.wheel.force-include]
"src/outlook_client_service/py.typed" = "outlook_client_service/py.typed"

[tool.uv.sources]
calendar-client-api = { workspace = true }
outlook-client-impl = { workspace = true }
intelligent-app-service = { workspace = true }
chat-client-api = { git = "https://github.com/HarshithKoriRaj/CS-GY-9223-Open-Source", branch = "feat/hw3", subdirectory = "components/chat_client_api" }
slack-client-impl = { git = "https://github.com/HarshithKoriRaj/CS-GY-9223-Open-Source", branch = "feat/hw3", subdirectory = "components/slack_client_impl" }